version: '3.7'


services:
  
  patient:
    build: ./PatientService 
    ports:
      - "4000:4000"
    volumes:
      - ./config:/app/PatientService/config

  doctor:
    build: ./DoctorService 
    ports:
      - "6000:6000"
    volumes:
      - ./config:/app/DoctorService/config

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - patient
      - admin  
  kafka:
    image: landoop/fast-data-dev:latest
    ports:
      - "2182:2182"
      - "3031:3031"
      - "8084-8087:8084-8087"
      - "9595:9585"
      - "9092:9092"
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=M1u2h3a4
      
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  admin:
      build: ./AdminService
      ports:
        - "3000:3000"
      volumes:
        - ./config:/app/AdminService/config
      depends_on:
        - doctor

volumes:
  config:
  db:
    driver: local

